apiVersion: mysql.oracle.com/v1alpha1
kind: Cluster
metadata:
  name: mysql
  namespace: default
spec:
  version: "8.0.11"
  mysqlServer: store/oracle/mysql-enterprise-server
  imagePullSecret: 
    name: myregistrykey
