apiVersion: mysql.oracle.com/v1alpha1
kind: BackupSchedule
metadata:
  name: mysql-backup-schedule
spec:
  schedule: '30 * * * *'
  backupTemplate:
    executor:
      name: mysqldump
      databases:
        - test
    storageProvider:
      name: s3
      secretRef:
        name: s3-credentials
      config:
        endpoint: ocitenancy.compat.objectstorage.ociregion.oraclecloud.com
        region: ociregion
        bucket: mybucket
    cluster:
      name: mysql
