apiVersion: mysql.oracle.com/v1alpha1
kind: Backup
metadata:
  name: mysql-backup
spec:
  executor:
    name: mysqldump
    databases:
      - test
  storageProvider:
    s3:
      endpoint: ocitenancy.compat.objectstorage.ociregion.oraclecloud.com
      region:   ociregion
      bucket:   mybucket
      credentialsSecret:
        name: s3-credentials
  clusterRef:
    name: mysql
