apiVersion: "mysql.oracle.com/v1"
kind: MySQLBackup
metadata:
  name: example-backup
spec:
  executor:
    provider: mysqldump
    databases:
      - test
  storage:
    provider: s3  
    cluster:
      name: mysql
    secretRef:
      name: oci-s3-credentials
    config:					
      endpoint: ocitenancy.compat.objectstorage.ociregion.oraclecloud.com
      region:   ociregion
      bucket:   mybucket
