apiVersion: "mysql.oracle.com/v1"
kind: MySQLBackupSchedule
metadata:
  name: mysql
spec:
  schedule: '30 * * * *'
  backupTemplate:
    executor:
      provider: mysqldump
      databases:
        - test
    storage:
      provider: s3  
      clusterRef:
        name: mysql
      secretRef:
        name: oci-s3-credentials
      config:
        endpoint: ocitenancy.compat.objectstorage.ociregion.oraclecloud.com
        region: ociregion
        bucket: mybucket
