apiVersion: mysql.oracle.com/v1alpha1
kind: Backup
metadata:
  name: mysql-backup
spec:
  executor:
    name: mysqldump
    databases:
      - test
  storageProvider:
    name: s3
    secretRef:
      name: s3-credentials
    config:
      endpoint: ocitenancy.compat.objectstorage.ociregion.oraclecloud.com
      region:   ociregion
      bucket:   mybucket
  clusterRef:
    name: mysql
